spring:
  profiles:
    active: dev,secret # ??? ????? ???? ?????.
            # ??: dev -> application-dev.yml ???? ??
  application:
    name: spring_boot_jpa_example # ?????? ??
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    problem-details:
      enabled: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB # 5MB ??? ??? ???? ?????.
      max-file-size: 30MB # ???? ?? ??? ?? ??? 30MB? ?????.
      max-request-size: 30MB # ?? HTTP ??? ?? ??? 30MB? ?????.
      location: / # ???? ??? ??? ??? ????? ?????.
  thymeleaf:
    enabled: true # Thymeleaf ??? (???: true)
    cache: false # ?? ????? ?? ???? (???: true)
    prefix: classpath:/templates/ # HTML ??? ?? ??
    suffix: .html # ??? ?? ???
    mode: HTML # ?? ?? (???: HTML)
    encoding: UTF-8 # ??? ??? ?? ???
    servlet:
      content-type: text/html # ?? Content-Type ??