spring:
  profiles:
    active: dev,secret # ??? ??? application.yml? ??
            # ??: dev -> application-dev.yml? ????? ???? ?? ??
            # ?, ??? application.yml(?? ??)? ??? ???? ???? ?? ??
            # ?? ??? ??? ?? dev,secret ? ?? ?? ??
  application:
    name: spring_boot_jpa_example # ???? ??
  mvc:
    problem-details:
      enabled: true # REST API?? ?? ??? ???? ??(JSON)?? ???? ?? ??? ??
  servlet:
    multipart:
      enabled: true # ?? ??? ??? ???
      file-size-threshold: 5MB # ?? ?? ???? ??, 5MB ??? ??? ???? ??
      max-file-size: 30MB # ???? ?? ??? ?? ??? 30MB? ??
      max-request-size: 30MB # ?? HTTP ??? ?? ??? 30MB? ??
      location: / # ???? ??? ??? ??? ????. /? ?? ?? ????? ??