server:
  port: 8081
  servlet:
    encoding:
      force-response: true
spring:
  application:
    name: spring-boot-pure
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        default-batch-fetch-size: 500
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    check-template-location: false
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql: trace
    kr.nomadhuns.spring_boot_pure: debug