server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://url:3306/pure?useUnicode=true&characterEncoding=utf8mb4&collation=utf8mb4_general_ci
        # jdbc:사용하는db://데이터베이스주소:데이터베이스포트번호/데이터베이스명
        # ?useUnicode=true&characterEncoding=utf8mb4&collation=utf8mb4_general_ci 해당 부분은 utf8(한글 사용가능) 을적용하기 위한 부분
        # 예시: jdbc:mysql://192.168.2.101:3306/test_db?useUnicode=true&characterEncoding=utf8mb4&collation=utf8mb4_general_ci
    driverClassName: org.mariadb.jdbc.Driver # 데이터베이스 driver 지정, 해당 데이터베이스 라이브러리를 build.gradle에 추가해야 사용할 수 있음.
    username: username # 데이터베이스 계정 이름
    password: password # 데이터베이스 계정 비밀번호
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect # 네이티브 쿼리 사용시 어떤 데이터베이스 쿼리를 사용할 것인지 지정
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default-batch-fetch-size: 500
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql.BasicBinder: warn
    org.hibernate.type.descriptor.sql: warn
    org.hibernate.engine.query.spi: warn
    org.hibernate.event.internal: warn
    kr.nomadhuns.spring_boot_pure: warn